# practice preparing/ wrangling messy dataset in a standardized way
>
> (Quote from Hould)
>
> The structure Wickham defines as tidy has the following attributes:
>
> Each variable forms a column and contains values
> 
> Each observation forms a row
>
> Each type of observational unit forms a table

In [1]:
import pandas as pd
import datetime
from os import listdir
from os.path import isfile, join
import glob
import re

## Column headers are values, not variable names.

In [8]:
df = pd.read_clipboard()
df

                  religion  <$10k  $10-20k  $20-30k  $30-40k  $40-50k  $50-75k
0                 Agnostic     27       34       60       81       76      137
1                  Atheist     12       27       37       52       35       70
2                 Buddhist     27       21       30       34       33       58
3                 Catholic    418      617      732      670      638     1116
4        Dont know/refused     15       14       15       11       10       35
5         Evangelical Prot    575      869     1064      982      881     1486
6                    Hindu      1        9        7        9       11       34
7  Historically Black Prot    228      244      236      238      197      223
8         Jehovahs Witness     20       27       24       24       21       30
9                   Jewish     19       19       25       25       30       95

In [6]:
# observation: even without using histogram, 
# we can roughly see the trend of income groups underlying each religion
clean_df = pd.melt(df, ["religion"],
                  var_name = "income",
                  value_name = "freq")
clean_df = clean_df.sort_values(by = ["religion"]).reset_index()
clean_df

    index                 religion   income  freq
0       0                 Agnostic    <$10k    27
1      30                 Agnostic  $30-40k    81
2      40                 Agnostic  $40-50k    76
3      50                 Agnostic  $50-75k   137
4      10                 Agnostic  $10-20k    34
5      20                 Agnostic  $20-30k    60
6      41                  Atheist  $40-50k    35
7      21                  Atheist  $20-30k    37
8      11                  Atheist  $10-20k    27
9      31                  Atheist  $30-40k    52
10      1                  Atheist    <$10k    12
11     51                  Atheist  $50-75k    70
12     42                 Buddhist  $40-50k    33
13      2                 Buddhist    <$10k    27
14     12                 Buddhist  $10-20k    21
15     32                 Buddhist  $30-40k    34
16     52                 Buddhist  $50-75k    58
17     22                 Buddhist  $20-30k    30
18     43                 Catholic  $40-50k   638
19     33                 Catholic  $30-40k   670
20     23                 Catholic  $20-30k   732
21     53                 Catholic  $50-75k  1116
22     13                 Catholic  $10-20k   617
23      3                 Catholic    <$10k   418
24     24        Dont know/refused  $20-30k    15
25     44        Dont know/refused  $40-50k    10
26      4        Dont know/refused    <$10k    15
27     54        Dont know/refused  $50-75k    35
28     14        Dont know/refused  $10-20k    14
29     34        Dont know/refused  $30-40k    11
30     25         Evangelical Prot  $20-30k  1064
31     55         Evangelical Prot  $50-75k  1486
32     15         Evangelical Prot  $10-20k   869
33      5         Evangelical Prot    <$10k   575
34     45         Evangelical Prot  $40-50k   881
35     35         Evangelical Prot  $30-40k   982
36     56                    Hindu  $50-75k    34
37     26                    Hindu  $20-30k     7
38     46                    Hindu  $40-50k    11
39     16                    Hindu  $10-20k     9
40     36                    Hindu  $30-40k     9
41      6                    Hindu    <$10k     1
42     47  Historically Black Prot  $40-50k   197
43     37  Historically Black Prot  $30-40k   238
44     57  Historically Black Prot  $50-75k   223
45     27  Historically Black Prot  $20-30k   236
46     17  Historically Black Prot  $10-20k   244
47      7  Historically Black Prot    <$10k   228
48      8         Jehovahs Witness    <$10k    20
49     38         Jehovahs Witness  $30-40k    24
50     58         Jehovahs Witness  $50-75k    30
51     48         Jehovahs Witness  $40-50k    21
52     28         Jehovahs Witness  $20-30k    24
53     18         Jehovahs Witness  $10-20k    27
54     29                   Jewish  $20-30k    25
55     39                   Jewish  $30-40k    25
56     19                   Jewish  $10-20k    19
57      9                   Jewish    <$10k    19
58     49                   Jewish  $40-50k    30
59     59                   Jewish  $50-75k    95

## Multiple variables are stored in one column.

## Variables are stored in both rows and columns.

## Multiple types of observational units are stored in the same table.

## A single observational unit is stored in multiple tables.